apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: a2
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 858633162811.dkr.ecr.us-east-1.amazonaws.com/my-mysql-repo:latest
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306
