apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: a2
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 858633162811.dkr.ecr.us-east-1.amazonaws.com/my-mysql-repo:latest
    imagePullPolicy: Never
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306
