apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: a2
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 858633162811.dkr.ecr.us-east-1.amazonaws.com/my-webapp-repo:latest
    imagePullPolicy: Never
    env:
    - name: DBHOST
      value: "mysql-service"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "blue"
    ports:
    - containerPort: 8080

