apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: a2
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 858633162811.dkr.ecr.us-east-1.amazonaws.com/my-webapp-repo:v0.1
        imagePullPolicy: Never
        env:
        - name: DBHOST
          value: "mysql-service"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"
        ports:
        - containerPort: 8080

