name: Deploy to ECR

on:
  push:
    branches:
      - Trigger-GitHub-Action-to-Push-Images

jobs:
  build:
    name: Build and Deploy Images to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Debug Region - MySQL
        run: |
          echo "AWS_DEFAULT_REGION (MySQL): ${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Create MySQL Repository if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names my-mysql-repo --region ${{ secrets.AWS_DEFAULT_REGION }} || aws ecr create-repository --repository-name my-mysql-repo --region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Debug Region - WebApp
        run: |
          echo "AWS_DEFAULT_REGION (WebApp): ${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Create WebApp Repository if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names my-webapp-repo --region ${{ secrets.AWS_DEFAULT_REGION }} || aws ecr create-repository --repository-name my-webapp-repo --region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Build, Tag, and Push MySQL Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          MYSQL_ECR_REPOSITORY: my-mysql-repo
          MYSQL_IMAGE_TAG: latest
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "Building MySQL Image.."
          docker build -f Dockerfile_mysql -t $ECR_REGISTRY/$MYSQL_ECR_REPOSITORY:$MYSQL_IMAGE_TAG .

          echo "Pushing MySQL Image to ECR..."
          docker push $ECR_REGISTRY/$MYSQL_ECR_REPOSITORY:$MYSQL_IMAGE_TAG

      - name: Build, Tag, and Push WebApp Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          WEBAPP_ECR_REPOSITORY: my-webapp-repo
          WEBAPP_IMAGE_TAG: latest
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "Building WebApp Image..."
          docker build -f Dockerfile -t $ECR_REGISTRY/$WEBAPP_ECR_REPOSITORY:$WEBAPP_IMAGE_TAG .

          echo "Pushing WebApp Image to ECR..."
          docker push $ECR_REGISTRY/$WEBAPP_ECR_REPOSITORY:$WEBAPP_IMAGE_TAG

      - name: Test Region - STS
        run: |
          echo "AWS_DEFAULT_REGION (STS Test): ${{ secrets.AWS_DEFAULT_REGION }}"
          aws sts get-caller-identity --region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: AWS CLI Version
        run: aws --version
